site_name: CalSMP Operator Feedback Portal
site_url: https://tony-held-carb.github.io/
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - content.code.annotate

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_docs.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

extra_css:
  - stylesheets/hide-sidebar-title.css  # keep this only if needed
  - stylesheets/extra.css
#  - stylesheets/force-panels.css
#  - stylesheets/fixes.css
#  - stylesheets/fix-sidebar-scroll.css