site_name: Arb Feedback Portal Documentation
site_url: https://your-github-username.github.io/your-repo-name
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotate
    - navigation.instant
  custom_dir: docs/overrides
  favicon: assets/favicon.ico

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_signature: true
            separate_signature: true
            heading_level: 2
            docstring_style: google
            merge_init_into_class: true

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Reference: reference/
